### ISSUE TITLE
Breadcrumb Navigation Support

### ISSUE THREAD

**Issue by harrywang** [oaeproject/3akai-ux#3868]
I had a discussion with Nicolaas about this earlier this year and still think this is an important feature for OAE. The current way of navigation can be quite confusing. Thanks.

**Comment by harrywang** [comment]
@nicolaasmatthijs any update on this issue? The current way of content navigation is quite confusing. Any estimate on when this feature can be added?

**Comment by nicolaasmatthijs** [comment]
Because of the problems with breadcrumbs on mobile devices, this work was not completed during the previous design burst. A new design burst is starting on January 9, during which this will be a priority again and further design and testing work will be done to uncover the most appropriate solution.
