### ISSUE TITLE
Why is ti not possible  for a tenant administrator to import user  by CSV File ?

### ISSUE THREAD

**Issue by dooremont** [oaeproject/3akai-ux#4093]
Why is ti not possible  for a tenant administrator to import user by CSV File ?

Patch ...   3akai-ux/oae-admin/usermanagement/usermanagement.html
line 40             {if context.isTenantOnGlobalAdminServer = true}

**Comment by mrvisser** [comment]
Hi Frederick, it's not allowed because the tools to reasonably fix bulk import mistakes are not available. Since the governance of an OAE instance can vary, it's not possible to know the skill level of tenant administrators with respect to sanitizing the CSV data they are importing, and so allowing unsupervised bulk imports can be a significant support hazard at the global administrator level.

So, we chose to take the safe route and not make it available as easy in the tenant admin UI.

**Comment by nicolaasmatthijs** [comment]
As @mrvisser indicated, it is currently deliberately not there because we want to avoid tenant administrators from making user import mistakes (and then having to clean it all up). Therefore, I'm going to close this ticket. Feel free to reopen if this is something you absolutely need for the French deployment.
